### ISSUE TITLE
Upgrade rubies

### ISSUE THREAD

**Issue by matthee** [Sapphire-CM/Sapphire#429]
We a currently running on ruby 2.1.6 in production. Its official support has ended in march 2016. I think its time to upgrade 😉 

# Roadmap

* [x] Run specs against 2.3.8
* [x] Upgrade Staging to 2.3.8
* [x] Upgrade Production to 2.3.8
* [x] Remove 2.1.6 from travis.yml

# Additional Upgrades

* Passenger should be upgraded to the newest version as well
